// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (user_id, type, encrypted_payload, metadata)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, encrypted_payload, metadata, version, deleted, created_at, updated_at
`

type CreateItemParams struct {
	UserID           uuid.UUID
	Type             int16
	EncryptedPayload []byte
	Metadata         string
}

// CreateItem создаёт новую запись приватных данных и возвращает её.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.UserID,
		arg.Type,
		arg.EncryptedPayload,
		arg.Metadata,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EncryptedPayload,
		&i.Metadata,
		&i.Version,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
UPDATE items
SET deleted = TRUE, version = version + 1, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DeleteItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// DeleteItem выполняет мягкое удаление записи.
// Выполняется update c флагом удаления true
func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteItem, arg.ID, arg.UserID)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, user_id, type, encrypted_payload, metadata, version, deleted, created_at, updated_at FROM items
WHERE id = $1 AND user_id = $2 AND NOT deleted
`

type GetItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// GetItem возвращает запись пользователя по id, исключая мягко удалённые.
func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, arg.ID, arg.UserID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EncryptedPayload,
		&i.Metadata,
		&i.Version,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, user_id, type, encrypted_payload, metadata, version, deleted, created_at, updated_at FROM items
WHERE user_id = $1 AND NOT deleted
ORDER BY updated_at DESC
`

// ListItems возвращает все неудалённые записи пользователя.
func (q *Queries) ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EncryptedPayload,
			&i.Metadata,
			&i.Version,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET encrypted_payload = $3,
    metadata = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND version = $5 AND NOT deleted
RETURNING id, user_id, type, encrypted_payload, metadata, version, deleted, created_at, updated_at
`

type UpdateItemParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	EncryptedPayload []byte
	Metadata         string
	Version          int64
}

// UpdateItem обновляет запись с проверкой версии.
// Если версия не совпала, ни одна строка не будет затронута.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.UserID,
		arg.EncryptedPayload,
		arg.Metadata,
		arg.Version,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EncryptedPayload,
		&i.Metadata,
		&i.Version,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
