// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

// Приватные данные пользователей: зашифрованный payload + открытая метаинформация
type Item struct {
	ID uuid.UUID
	// Владелец записи, FK на users.id
	UserID uuid.UUID
	// Тип данных: 1=credentials, 2=text, 3=binary, 4=card
	Type int16
	// Зашифрованные данные пользователя
	EncryptedPayload []byte
	// Открытая текстовая метаинформация: сайт, банк, личность и т.п.
	Metadata string
	// Версия записи
	Version int64
	// Удалена ли запись
	Deleted   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Зарегистрированные пользователи системы
type User struct {
	// Идентификатор пользователя, генерируется БД
	ID uuid.UUID
	// Уникальный логин для входа
	Login string
	// Хеш пароля пользователя
	PasswordHash string
	// Дата и время регистрации
	CreatedAt time.Time
}
