// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// CreateItem создаёт новую запись приватных данных и возвращает её.
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	// CreateUser создаёт нового пользователя и возвращает его данные без хеша пароля.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// DeleteItem выполняет мягкое удаление записи.
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	// GetItem возвращает запись пользователя по id, исключая мягко удалённые.
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	// GetUserByLogin возвращает пользователя по логину вместе с password_hash для сверки при входе.
	GetUserByLogin(ctx context.Context, login string) (User, error)
	// ListItems возвращает все неудалённые записи пользователя.
	ListItems(ctx context.Context, userID uuid.UUID) ([]Item, error)
	// UpdateItem обновляет запись с проверкой версии.
	// Если версия не совпала, ни одна строка не будет затронута.
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
