// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, password_hash)
VALUES ($1, $2)
RETURNING id, login, created_at
`

type CreateUserParams struct {
	Login        string
	PasswordHash string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Login     string
	CreatedAt time.Time
}

// CreateUser создаёт нового пользователя и возвращает его данные без хеша пароля.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Login, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Login, &i.CreatedAt)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, password_hash, created_at
FROM users
WHERE login = $1
`

// GetUserByLogin возвращает пользователя по логину вместе с password_hash для сверки при входе.
func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
