// Code generated by MockGen. DO NOT EDIT.
// Source: keeper_handler.go
//
// Generated by this command:
//
//	mockgen -source=keeper_handler.go -destination=mocks/mock_keep_service.go -package=mocks KeepService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/kkapel/gophkeeper/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockKeepService is a mock of KeepService interface.
type MockKeepService struct {
	ctrl     *gomock.Controller
	recorder *MockKeepServiceMockRecorder
	isgomock struct{}
}

// MockKeepServiceMockRecorder is the mock recorder for MockKeepService.
type MockKeepServiceMockRecorder struct {
	mock *MockKeepService
}

// NewMockKeepService creates a new mock instance.
func NewMockKeepService(ctrl *gomock.Controller) *MockKeepService {
	mock := &MockKeepService{ctrl: ctrl}
	mock.recorder = &MockKeepServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeepService) EXPECT() *MockKeepServiceMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MockKeepService) CreateItem(ctx context.Context, userID uuid.UUID, itemType int16, encryptedPayload []byte, metadata string) (domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, userID, itemType, encryptedPayload, metadata)
	ret0, _ := ret[0].(domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockKeepServiceMockRecorder) CreateItem(ctx, userID, itemType, encryptedPayload, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockKeepService)(nil).CreateItem), ctx, userID, itemType, encryptedPayload, metadata)
}

// DeleteItem mocks base method.
func (m *MockKeepService) DeleteItem(ctx context.Context, userID, itemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockKeepServiceMockRecorder) DeleteItem(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockKeepService)(nil).DeleteItem), ctx, userID, itemID)
}

// GetItem mocks base method.
func (m *MockKeepService) GetItem(ctx context.Context, userID, itemID uuid.UUID) (domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, userID, itemID)
	ret0, _ := ret[0].(domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockKeepServiceMockRecorder) GetItem(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockKeepService)(nil).GetItem), ctx, userID, itemID)
}

// ListItems mocks base method.
func (m *MockKeepService) ListItems(ctx context.Context, userID uuid.UUID) ([]domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, userID)
	ret0, _ := ret[0].([]domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockKeepServiceMockRecorder) ListItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockKeepService)(nil).ListItems), ctx, userID)
}

// UpdateItem mocks base method.
func (m *MockKeepService) UpdateItem(ctx context.Context, userID, itemID uuid.UUID, payload []byte, metadata string, version int64) (domain.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, userID, itemID, payload, metadata, version)
	ret0, _ := ret[0].(domain.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockKeepServiceMockRecorder) UpdateItem(ctx, userID, itemID, payload, metadata, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockKeepService)(nil).UpdateItem), ctx, userID, itemID, payload, metadata, version)
}
